services:
  _defaults:
    public: true

  netzmacht.contao_form_designer.listener.contextual_form_layout:
    class: Netzmacht\Contao\FormDesigner\Listener\ContextualFormLayoutListener
    arguments:
      - '@netzmacht.contao_form_designer.layout_manager'
      - '@netzmacht.contao_form_designer.repository.layout'
      - '@netzmacht.contao_form_designer.layout_factory'
      - '@netzmacht.contao_form_designer.repository.form'
      - '@contao.framework'
      - '@logger'
      - '%netzmacht.contao_form_designer.form_designer.modules%'
      - '%netzmacht.contao_form_designer.form_designer.elements%'
      - '@contao.routing.scope_matcher'
      - '@request_stack'
    tags:
      - { name: kernel.event_listener, event: 'netzmacht.contao_form_designer.select_layout', method: onSelectLayout }

  netzmacht.contao_form_designer.listener.theme_form_layout:
    class: Netzmacht\Contao\FormDesigner\Listener\ThemeFormLayoutListener
    arguments:
      - '@netzmacht.contao_form_designer.layout_manager'
      - '@netzmacht.contao_form_designer.repository.layout'
      - '@netzmacht.contao_form_designer.layout_factory'
      - '@logger'

  netzmacht.contao_form_designer.listener.theme_export:
    class: Netzmacht\Contao\FormDesigner\Listener\ThemeExportListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'

  netzmacht.contao_form_designer.listener.theme_import:
    class: Netzmacht\Contao\FormDesigner\Listener\ThemeImportListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'

  netzmacht.contao_form_designer.listener.dca.form:
    class: Netzmacht\Contao\FormDesigner\Listener\Dca\FormListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'

  netzmacht.contao_form_designer.listener.dca.form_field:
    class: Netzmacht\Contao\FormDesigner\Listener\Dca\FormFieldListener
    arguments:
      - '%netzmacht.contao_form_designer.widgets%'

  netzmacht.contao_form_designer.listener.dca.form_layout:
    class: Netzmacht\Contao\FormDesigner\Listener\Dca\FormLayoutListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'
      - '@netzmacht.contao_form_designer.layout_factory'
      - '@contao.framework'
      - '%netzmacht.contao_form_designer.form_designer.virtual_widgets%'

  netzmacht.contao_form_designer.listener.dca.module:
    class: Netzmacht\Contao\FormDesigner\Listener\Dca\ModuleListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'
      - '%netzmacht.contao_form_designer.form_designer.modules%'

  netzmacht.contao_form_designer.listener.dca.content:
    class: Netzmacht\Contao\FormDesigner\Listener\Dca\ContentListener
    arguments:
      - '@netzmacht.contao_form_designer.repository.layout'
      - '%netzmacht.contao_form_designer.form_designer.elements%'
